name: daily-automatic-update
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

env:
  USERNAME: ${{ secrets.USERNAME }}
  TOKEN: ${{ secrets.TOKEN }}
  NAME: ${{ secrets.NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

jobs:

  daily-automatic-update:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Setting up build version
        run: |
          version=$(($GITHUB_RUN_NUMBER))
          echo "BUILD_VERSION=2.2.$version" >> ${GITHUB_ENV}

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run
        run: dotnet run --project src/Soenneker.Runners.ZipCode.csproj --no-restore --verbosity normal --framework net9.0
